version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_URL=redis://redis:6379/0
    command: ["sh", "./entrypoint.sh", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]

  sidekiq:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - web # Asegura que 'web' se inicie antes
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_URL=redis://redis:6379/0
    command: ["sh", "./entrypoint.sh", "bundle", "exec", "sidekiq"]

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

volumes:
  postgres_data:
