---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/gps":
    post:
      summary: Create a GPS waypoint
      tags:
      - GPS
      parameters: []
      responses:
        '201':
          description: Waypoint created successfully
        '422':
          description: Validation errors
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                latitude:
                  type: number
                  example: 20.23
                longitude:
                  type: number
                  example: -0.56
                sent_at:
                  type: string
                  format: date_time
                  example: '2016-06-02T20:45:00Z'
                vehicle_identifier:
                  type: string
                  example: HA-3452
              required:
              - latitude
              - longitude
              - sent_at
              - vehicle_identifier
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: http://localhost:3000
